### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "superman"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/countries

###

GET {{url}}/countries/2

###

POST {{url}}/countries
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Argentina",
  "currencies": [
    "Argentine peso"
  ],
  "capital": "Buenos Aires",
  "languages": [
    "Spanish"
  ],
  "borders": [
    "BOL",
    "BRA",
    "CHL",
    "PRY",
    "URY"
  ],
  "area": 2780400.0,
  "googleMaps": "https://goo.gl/maps/Fu9Ppnvn3cK6cxKK6",
  "population": 45376763,
  "flagPng": "https://flagcdn.com/w320/ar.png"
}

###

PUT {{url}}/countries/3
Content-Type: application/json

{
  "name": "Paraguay",
  "currencies": [
    "Argentine peso"
  ],
  "capital": "Buenos Aires",
  "languages": [
    "Spanish"
  ],
  "borders": [
    "BOL",
    "BRA",
    "CHL",
    "PRY",
    "URY"
  ],
  "area": 2780400.0,
  "googleMaps": "https://goo.gl/maps/Fu9Ppnvn3cK6cxKK6",
  "population": 45376763,
  "flagPng": "https://flagcdn.com/w320/ar.png"
}

###

DELETE {{url}}/countries/3

###

GET {{url}}/countries/populate